### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by bhagwatposane** [kenfar/DataGristle#62]
Hello,
Please find the attachment for the errors.
![windows error](https://user-images.githubusercontent.com/29473793/33823493-53149cf8-de81-11e7-8d5e-52c23f1372b8.png)

**Comment by kenfar** [comment]
Can you tell me what version you're running?  Did you just install this from pypi?   Otherwise, please run this command to get the version:

$ gristle_differ --version

Also, this software has not been tested on windows.   Most of it should work fine, but there could be problems.

Finally, gristle_determinator doesn't accept a '-f' option.
